shared:
    image: node:18
    annotations:
        publish: &publish
            steps:
                - install: npm install screwdriver-template-main
                - publish: ./node_modules/.bin/pipeline-template-publish
        validate: &validate
            steps:
                - install: npm install screwdriver-template-main
                - validate: ./node_modules/.bin/pipeline-template-validate
jobs:
    publish-test:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-publish-test-pipeline-template.yaml
    publish-invalid:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-invalid-pipeline-template.yaml
    publish-trusted:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-trusted-pipeline-template.yaml
    publish-distrusted:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-distrusted-pipeline-template.yaml
    validate-valid:
        <<: *validate
        environment:
            SD_TEMPLATE_PATH: ./sd-init-pipeline-template.yaml
    validate-invalid:
        <<: *validate
        environment:
            SD_TEMPLATE_PATH: ./sd-invalid-pipeline-template.yaml
    init-test-pipeline-template:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-init-pipeline-template.yaml
    init-test-trusted-pipeline-template:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-trusted-pipeline-template.yaml
    init-test-distrusted-pipeline-template:
        <<: *publish
        environment:
            SD_TEMPLATE_PATH: ./sd-distrusted-pipeline-template.yaml
